/**
 * @file hw_board_v2_0.h
 * @brief Hardware pin definitions for AT-USB LoRa Dongle v2.0
 * @date 2026-01-13
 *
 * Changes from v1.0:
 * - SX1262_RF_SW moved from PB12 to PA8 (example - update with actual changes)
 */

#ifndef HW_BOARD_V2_0_H
#define HW_BOARD_V2_0_H

/* Board version */
#define HW_BOARD_VERSION_MAJOR  2
#define HW_BOARD_VERSION_MINOR  0
#define HW_BOARD_VERSION_STRING "v2.0"

/* ============================================================================
 * Pin overrides for v2.0 hardware
 * ============================================================================
 * These definitions override pins from main.h (generated by STM32CubeMX)
 * Only changed pins need to be listed here.
 */

/* CHANGED in v2.0: RF_SW moved from PB12 to PA8 */
#undef SX1262_RF_SW_Pin
#undef SX1262_RF_SW_GPIO_Port
#define SX1262_RF_SW_Pin GPIO_PIN_8
#define SX1262_RF_SW_GPIO_Port GPIOA

#endif /* HW_BOARD_V2_0_H */
